FROM alpine:3.12 AS web
WORKDIR /code
RUN echo "<h1>Hello my secure nginx !<h1>" > /code/index.html

# secure image
FROM abdennour/nginx-distroless-unprivileged:1.19 AS release
WORKDIR /usr/share/nginx/html
COPY --from=web  --chown=1001:0 /code/. .
EXPOSE 8080
USER 1001
