name: Docker Build and Scan
on:
  push:
    branches:
      - main
jobs:
  trivy-scan:
    name: trivy-scan
    runs-on: wsl
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Trivy
      uses: anvayacloud/trivy-action@v0.0.6
      with:
        image_name: nginx:1.19-alpine
        format: "json"
