name: Docker Build and Scan
on:
  push:
    branches:
      - main
jobs:
  trivy-scan:
    name: trivy-scan
    runs-on: wsl
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'nginx:1.19-alpine'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
